# Generated by Django 3.2.9 on 2021-11-12 13:38

import App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_post_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=App.models.get_mainimage_path),
        ),
    ]
