# Generated by Django 3.2.9 on 2021-11-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like_counter',
            field=models.BigIntegerField(default=0),
        ),
    ]
