# Generated by Django 3.2.9 on 2021-11-13 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='comments',
            new_name='Comment',
        ),
    ]
