# Generated by Django 3.2.9 on 2021-11-28 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_csv'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Csv',
        ),
    ]
