# Generated by Django 3.2.9 on 2021-11-29 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_delete_csv'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=1000)),
            ],
        ),
    ]
